# Note: You can use any Debian/Ubuntu based image you want. 
FROM swift:6.2.0

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends make