name: 'Run Swift Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ENABLE_LOGGING : "true"
  AWS_LOG_LEVEL: "trace"

jobs:
  swift-tests:
    name: 'Swift Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.10.1
    container:
      image: ${{ matrix.image }}
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup 
        run:  |
          export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && apt-get -q install -y make curl wget
      - name: Test
        run: |
          make test
      - name: Coverage
        run: |
          make coverage
      - name: Upload Code Coverage 
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/lcov.info