name: 'Run Swift Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ENABLE_LOGGING : "true"
  AWS_LOG_LEVEL: "trace"

jobs:
  swift-tests:
    name: 'Swift Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.7.3-amazonlinux2
    container:
      image: ${{ matrix.image }}
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup 
        run:  |
          yum -y update && yum -y install git make curl
      - name: Test
        run: |
          make test
      - name: Coverage
        run: |
          make coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: swift-serverless/BreezeLambdaWebHook
          files: ${{ github.workspace }}/lcov.info